In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
!unzip -q "/content/gdrive/MyDrive/wavfiles/embeddings.zip"


In [3]:
audio_folder="/content/embeddings/"

In [4]:
import os
data1folder=os.listdir(audio_folder)

In [5]:
data1folder

['Ses01M_impro06_M023.npy',
 'Ses04F_script03_2_F044.npy',
 'Ses02F_impro07_F019.npy',
 'Ses03M_impro07_F001.npy',
 'Ses02M_impro04_M011.npy',
 'Ses03F_impro01_F006.npy',
 'Ses05F_script03_2_M006.npy',
 'Ses02F_impro05_F022.npy',
 'Ses01F_script02_1_M032.npy',
 'Ses04F_script03_1_M022.npy',
 'Ses01M_script02_2_M029.npy',
 'Ses04F_impro04_M005.npy',
 'Ses03F_script03_2_F013.npy',
 'Ses02F_script02_1_M007.npy',
 'Ses01M_script02_2_M043.npy',
 'Ses03F_script01_3_F007.npy',
 'Ses02M_impro01_M009.npy',
 'Ses03F_script01_2_F019.npy',
 'Ses03F_impro01_M003.npy',
 'Ses03F_script01_2_M003.npy',
 'Ses05M_script03_1_M010.npy',
 'Ses02M_impro08_F002.npy',
 'Ses03F_impro04_M019.npy',
 'Ses01M_impro07_M030.npy',
 'Ses02M_script02_1_M040.npy',
 'Ses04M_script01_2_M016.npy',
 'Ses04M_impro06_M016.npy',
 'Ses03F_script02_2_M045.npy',
 'Ses05M_impro06_M007.npy',
 'Ses05M_impro03_M011.npy',
 'Ses01F_impro05_M033.npy',
 'Ses05F_impro02_M041.npy',
 'Ses05F_script01_3_F009.npy',
 'Ses02F_script01_1_M028.npy

In [6]:
import torch
import librosa
import numpy as np
embeds="/content/embeddings/"
files = librosa.util.find_files(embeds, ext=['npy']) 
files = np.asarray(files)
type(files)
meanembeds=[]
for i in files:
  emb1=np.load(i)
  a=torch.tensor(emb1)
  prediction = a.mean(1)
  print(prediction)
  print(prediction.shape)
  meanembeds.append(prediction)

Streaming output truncated to the last 5000 lines.
tensor([[  7.9422, -21.1497, -21.0204, -21.0696,   1.4395,   0.3255,  -1.1814,
          -0.4406,  -0.8673,  -0.6002,  -0.5156,  -0.9445,  -2.6646,  -2.1691,
          -2.2309,  -1.5016,  -1.5790,  -2.4038,  -1.3873,  -4.0524,  -4.1975,
          -3.0016,  -1.5471,  -4.1837,  -3.5665,  -4.6118,  -3.7909,  -1.7228,
          -6.9793,  -5.5146,  -6.9286,  -6.5136]])
torch.Size([1, 32])
tensor([[ 7.3518e+00, -2.1375e+01, -2.1244e+01, -2.1325e+01,  1.5807e+00,
          1.5286e-02, -2.9412e-01, -8.3038e-01, -9.3457e-01, -7.1995e-02,
         -8.0626e-01, -6.6245e-01, -2.9501e+00, -1.9579e+00, -1.4368e+00,
         -1.8280e+00, -1.7774e+00, -1.9751e+00, -2.0852e+00, -4.0420e+00,
         -3.7367e+00, -2.2543e+00, -1.8063e+00, -3.1537e+00, -2.6472e+00,
         -4.3230e+00, -3.4970e+00, -1.9379e+00, -6.9661e+00, -4.9575e+00,
         -6.8952e+00, -6.2657e+00]])
torch.Size([1, 32])
tensor([[  8.0352, -21.3241, -21.1884, -21.2363,   0.7206,  -

In [7]:
meanembeds

[tensor([[ 10.2650, -23.7845, -23.5158, -23.6307,   0.6292,  -0.8756,  -1.1795,
           -2.1640,  -3.0192,  -2.0100,  -1.0749,  -1.6233,  -1.8331,  -3.0282,
           -2.4041,  -2.4986,  -2.2611,  -2.9681,  -3.0374,  -3.8552,  -3.5169,
           -1.9775,  -3.6619,  -3.4610,  -2.5273,  -4.6329,  -4.7428,  -4.8503,
           -6.3165,  -5.4832,  -6.1702,  -5.0909]]),
 tensor([[ 12.0193, -24.1969, -23.9388, -24.0615,   0.0404,  -1.7703,  -1.4738,
           -2.2708,  -3.0962,  -2.6337,  -1.4207,  -1.8622,  -1.7482,  -3.2049,
           -3.2065,  -2.5472,  -3.0358,  -3.9128,  -4.1799,  -3.9811,  -4.2837,
           -3.5018,  -3.4716,  -2.7957,  -3.4496,  -5.8176,  -3.9505,  -4.1629,
           -7.0206,  -4.5151,  -6.2977,  -6.1847]]),
 tensor([[ 10.8978, -24.3673, -24.0969, -24.2180,   0.1845,  -1.1819,  -1.8055,
           -1.6234,  -2.2713,  -1.9520,  -1.4353,  -1.7282,  -2.0007,  -2.8390,
           -2.4450,  -2.5844,  -2.3079,  -2.4955,  -2.1442,  -4.5308,  -3.1934,
           -2.

In [8]:
embeddings=[]
for i in meanembeds:
  a=i.numpy()
  l=a[0]
  print(l)
  embeddings.append(l)

  

Streaming output truncated to the last 5000 lines.
  -6.254128    -6.7587185 ]
[  8.110912   -21.420744   -21.268684   -21.330797     1.7867844
  -0.08702141  -0.7030345   -1.0435932   -1.3902525   -1.4301643
  -1.2606404   -1.2559357   -2.3779793   -2.4710624   -1.2669208
  -1.6130837   -1.7655522   -3.4004335   -2.17101     -4.1960864
  -3.268345    -2.7778926   -1.6593597   -3.43194     -2.5577297
  -4.4629197   -3.616716    -1.6442777   -7.2048144   -5.6511254
  -7.2440224   -6.0826235 ]
[  9.059941  -21.651825  -21.451828  -21.507082    0.5934121  -0.8387672
  -0.6745812  -1.7287116  -2.1493087  -2.1490097  -0.5280789  -1.6057911
  -1.7298635  -2.599446   -2.2493968  -2.3077586  -2.4791412  -3.4352868
  -2.1687293  -3.5257502  -3.0433326  -2.170028   -2.244326   -2.9433405
  -3.0116138  -4.4567184  -3.3282125  -2.5412679  -6.6495132  -4.9433236
  -5.956214   -5.676804 ]
[  8.117431  -21.81562   -21.672218  -21.75407     1.2310069  -0.3218228
  -0.340205   -1.6395568  -0.832477   -

In [9]:
import pandas as pd
df = pd.DataFrame(columns=['embeddings'])

In [10]:
df['embeddings']=embeddings

In [11]:
df

embeddings
0      [10.264994, -23.784517, -23.515844, -23.630688...
1      [12.019276, -24.196888, -23.938843, -24.061504...
2      [10.897807, -24.367256, -24.09692, -24.218029,...
3      [9.627059, -22.097925, -21.901371, -21.990076,...
4      [8.844983, -23.588017, -23.4278, -23.490126, 0...
...                                                  ...
10034  [8.346877, -22.437504, -22.274395, -22.305025,...
10035  [8.06096, -22.289936, -22.14285, -22.228481, 1...
10036  [8.836262, -22.717813, -22.576782, -22.668253,...
10037  [7.265687, -21.073788, -20.937859, -20.993507,...
10038  [7.254952, -21.148144, -21.006895, -21.057905,...

[10039 rows x 1 columns]

In [12]:
from google.colab import files

uploaded = files.upload()

Saving data (1).csv to data (1).csv


In [13]:
import pandas as pd
dataset=pd.read_csv('/content/data (1).csv')
dataset



Unnamed: 0  start_time  end_time  ...     val     act     dom
0               0      7.2455   11.6400  ...  3.0000  3.0000  3.0000
1               1     11.7448   16.1500  ...  2.5000  2.5000  3.0000
2               2     18.6000   30.8976  ...  2.5000  3.5000  3.0000
3               3     35.0090   37.8000  ...  2.5000  3.0000  2.5000
4               4     40.2300   41.9500  ...  2.5000  2.5000  2.0000
...           ...         ...       ...  ...     ...     ...     ...
10034        2165    188.6500  199.4600  ...  2.3333  4.0000  2.6667
10035        2166    200.1000  202.3900  ...  3.6667  4.0000  2.3333
10036        2167    202.4500  207.4200  ...  2.6667  3.3333  3.3333
10037        2168    207.4300  212.1200  ...  3.0000  3.3333  3.3333
10038        2169    213.4500  217.5800  ...  3.3333  2.6667  2.3333

[10039 rows x 8 columns]

In [14]:
df_combined = pd.concat([dataset,pd.DataFrame(df['embeddings'])],axis=1)
#df_combined1= df_combined[df_combined.New_Emotions != 'Others']

In [15]:
df_combined
#df_combined1.New_Emotions.value_counts()

Unnamed: 0  ...                                         embeddings
0               0  ...  [10.264994, -23.784517, -23.515844, -23.630688...
1               1  ...  [12.019276, -24.196888, -23.938843, -24.061504...
2               2  ...  [10.897807, -24.367256, -24.09692, -24.218029,...
3               3  ...  [9.627059, -22.097925, -21.901371, -21.990076,...
4               4  ...  [8.844983, -23.588017, -23.4278, -23.490126, 0...
...           ...  ...                                                ...
10034        2165  ...  [8.346877, -22.437504, -22.274395, -22.305025,...
10035        2166  ...  [8.06096, -22.289936, -22.14285, -22.228481, 1...
10036        2167  ...  [8.836262, -22.717813, -22.576782, -22.668253,...
10037        2168  ...  [7.265687, -21.073788, -20.937859, -20.993507,...
10038        2169  ...  [7.254952, -21.148144, -21.006895, -21.057905,...

[10039 rows x 9 columns]

In [16]:
df_combined.isnull().sum()

Unnamed: 0    0
start_time    0
end_time      0
wav_file      0
emotion       0
val           0
act           0
dom           0
embeddings    0
dtype: int64

In [17]:
extracted_features_df=pd.DataFrame(df_combined,columns=['embeddings','emotion'])
extracted_features_df.head()

embeddings emotion
0  [10.264994, -23.784517, -23.515844, -23.630688...     neu
1  [12.019276, -24.196888, -23.938843, -24.061504...     neu
2  [10.897807, -24.367256, -24.09692, -24.218029,...     fru
3  [9.627059, -22.097925, -21.901371, -21.990076,...     xxx
4  [8.844983, -23.588017, -23.4278, -23.490126, 0...     xxx

In [18]:
X=np.array(extracted_features_df['embeddings'].tolist())
y=np.array(extracted_features_df['emotion'].tolist())

In [19]:
X.shape

(10039, 32)

In [20]:
y

array(['neu', 'neu', 'fru', ..., 'exc', 'xxx', 'xxx'], dtype='<U3')

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [22]:
X_train



array([[  9.203017 , -23.144302 , -22.959902 , ...,  -5.8237376,
         -6.922939 ,  -6.3995576],
       [  7.88225  , -22.784271 , -22.62624  , ...,  -5.919536 ,
         -7.419187 ,  -6.635112 ],
       [  9.174455 , -21.999863 , -21.82043  , ...,  -5.5305705,
         -6.633631 ,  -5.85072  ],
       ...,
       [  7.624012 , -20.08431  , -19.931751 , ...,  -5.148231 ,
         -6.404298 ,  -5.003526 ],
       [  8.446661 , -21.86066  , -21.686743 , ...,  -5.361583 ,
         -6.2291293,  -6.117202 ],
       [  9.648543 , -23.597471 , -23.432964 , ...,  -6.194709 ,
         -7.1952853,  -6.379382 ]], dtype=float32)

In [23]:
X_train.shape


(7529, 32)

In [24]:
X_test.shape

(2510, 32)

In [25]:
y_train.shape

(7529,)

In [26]:
y_test.shape

(2510,)

In [27]:
from sklearn.svm import SVC
classifier = SVC(C=0.001,kernel='poly', gamma=0.001)
classifier.fit(X_train, y_train)

SVC(C=0.001, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [30]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred)*100)

25.0199203187251
